@startuml state_diagram
allow_mixing

class State {
  State(GameManager _context)

  HandleEvent(Action currentAction)
}

class GameManager {
  State CurrentState

  TransitionTo(Action action, State newState)
}

State <- GameManager

enum Action
{
    ToggleMainMenu
    TogglePause
    OpenOptions
    ExitGame
}

Action <.. State

@enduml